

services:
  dev-postgres:
    image: postgres:latest
    container_name: dev-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: permission_system
    networks:
      - p_dev

  dev-redis:
    image: redis:latest
    container_name: dev-redis
    ports:
      - '6379:6379'
    networks:
      - p_dev
  
networks:
  p_dev: