

services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
      POSTGRES_DB: permission_system
    networks:
      - p_test

  test-redis:
    image: redis:latest
    container_name: test-redis
    ports:
      - '6380:6379'
    networks:
      - p_test
  
networks:
  p_test: